import type { Metadata } from "next";
import "../../globals.css";
import ProfileHeader from "@/components/UserPanel/Profile/ProfileHeader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ProfileHeader />
        {children}
      </body>
    </html>
  );
}
