import type { Metadata } from "next";
import "../../../../globals.css";
import CompleteHeader from "@/components/UserPanel/Profile/Reservation/Complete/CompleteHeader/CompleteHeader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <CompleteHeader />
        {children}
      </body>
    </html>
  );
}
